docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - Pages: pages.md
        - Containers: containers.md
        - View Helpers:
            - Intro: helpers/intro.md
            - Breadcrumbs: helpers/breadcrumbs.md
            - Links: helpers/links.md
            - Menu: helpers/menu.md
            - Sitemap: helpers/sitemap.md
            - "Navigation Proxy": helpers/navigation.md
site_name: laminas-navigation
site_description: laminas-navigation
repo_url: 'https://github.com/laminas/laminas-navigation'
